"""Compact expected extracts for every sample invoice (fields that drive pay/hold)."""

GOLDEN = {
    "invoice_1001.txt": {
        "invoice_id": "INV-1001",
        "vendor": "Widgets Inc.",
        "skus": [("WidgetA", 10.0), ("WidgetB", 5.0)],
        "total": 5000.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1002.txt": {
        "invoice_id": "INV-1002",
        "vendor": "Gadgets Co.",
        "skus": [("GadgetX", 20.0)],
        "total": 15000.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1003.txt": {
        "invoice_id": "INV-1003",
        "vendor": "Fraudster LLC",
        "skus": [("FakeItem", 100.0)],
        "total": 100000.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1004.json": {
        "invoice_id": "INV-1004",
        "vendor": "Precision Parts Ltd.",
        "skus": [("WidgetA", 3.0), ("WidgetB", 2.0)],
        "total": 1890.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1004_revised.json": {
        "invoice_id": "INV-1004",
        "vendor": "Precision Parts Ltd.",
        "skus": [("WidgetA", 3.0), ("WidgetB", 2.0), ("GadgetX", 5.0)],
        "total": 5940.0,
        "currency": "USD",
        "revision": "R1",
    },
    "invoice_1005.json": {
        "invoice_id": "INV-1005",
        "vendor": "Global Supply Chain Partners",
        "skus": [("WidgetA", 14.0), ("GadgetX", 8.0), ("WidgetB", 10.0)],
        "total": 15225.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1006.csv": {
        "invoice_id": "INV-1006",
        "vendor": "Acme Industrial Supplies",
        "skus": [("WidgetA", 5.0), ("WidgetB", 3.0)],
        "total": 2750.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1007.csv": {
        "invoice_id": "INV-1007",
        "vendor": "MegaWidgets Corp",
        "skus": [("WidgetA", 20.0), ("WidgetB", 15.0), ("GadgetX", 3.0)],
        "total": 15525.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1008.txt": {
        "invoice_id": "INV-1008",
        "vendor": "NoProd Industries",
        "skus": [("SuperGizmo", 12.0), ("MegaSprocket", 6.0)],
        "total": 9900.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1009.json": {
        "invoice_id": "INV-1009",
        "vendor": "",
        "skus": [("WidgetA", -5.0), ("WidgetB", 2.0)],
        "total": -250.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1010.txt": {
        "invoice_id": "INV-1010",
        "vendor": "Consolidated Materials Group",
        "skus": [("WidgetA", 8.0), ("WidgetB", 4.0), ("GadgetX", 2.0), ("WidgetA", 4.0)],
        "total": 7185.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1011.txt": {
        "invoice_id": "INV-1011",
        "vendor": "Summit Manufacturing Co.",
        "skus": [("WidgetA", 6.0), ("WidgetB", 3.0)],
        "total": 3000.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1011.pdf": {
        "invoice_id": "INV-1011",
        "vendor": "Summit Manufacturing Co.",
        "skus": [("WidgetA", 6.0), ("WidgetB", 3.0)],
        "total": 3000.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1012.txt": {
        "invoice_id": "INV-1012",
        "vendor": "QuickShip Distributers",
        "skus": [("WidgetA", 12.0), ("WidgetB", 7.0), ("GadgetX", 4.0)],
        "total": 9975.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1012.pdf": {
        "invoice_id": "INV-1012",
        "vendor": "QuickShip Distributers",
        "skus": [("WidgetA", 12.0), ("WidgetB", 7.0), ("GadgetX", 4.0)],
        "total": 9975.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1013.json": {
        "invoice_id": "INV-1013",
        "vendor": "Atlas Industrial Supply",
        "skus": [
            ("WidgetA", 15.0),
            ("WidgetB", 10.0),
            ("GadgetX", 5.0),
            ("WidgetA", 5.0),
            ("WidgetB", 8.0),
            ("GadgetX", 3.0),
            ("WidgetA", 2.0),
            ("GadgetX", 1.0),
        ],
        "total": 22562.80,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1013.pdf": {
        "invoice_id": "INV-1013",
        "vendor": "Atlas Industrial Supply",
        "skus": [
            ("WidgetA", 15.0),
            ("WidgetB", 10.0),
            ("GadgetX", 5.0),
            ("WidgetA", 5.0),
            ("WidgetB", 8.0),
            ("GadgetX", 3.0),
            ("WidgetA", 2.0),
            ("GadgetX", 1.0),
        ],
        "total": 22562.80,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1014.xml": {
        "invoice_id": "INV-1014",
        "vendor": "TechParts International",
        "skus": [("WidgetA", 4.0), ("WidgetB", 6.0)],
        "total": 4125.0,
        "currency": "EUR",
        "revision": None,
    },
    "invoice_1015.csv": {
        "invoice_id": "INV-1015",
        "vendor": "Reliable Components Inc.",
        "skus": [("WidgetA", 10.0), ("WidgetB", 5.0), ("GadgetX", 2.0)],
        "total": 6500.0,
        "currency": "USD",
        "revision": None,
    },
    "invoice_1016.json": {
        "invoice_id": "INV-1016",
        "vendor": "Widgets Inc.",
        "skus": [("WidgetA", 4.0), ("WidgetB", 2.0), ("WidgetC", 3.0)],
        "total": 3233.0,
        "currency": "USD",
        "revision": None,
    },
}
